package com.d4viddf.medicationreminder.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

// Old Baseline Palette (keeping for reference or if some colors are reused for error/background etc.)
val Purple40 = Color(0xFF6650a4) // Old primary example
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Specific existing colors (might be reused or replaced)
val DarkGreen = Color(0xFF264443)
val LightGreenAccent = Color(0xFFB4CFC6)
val OrangeAccent = Color(0xFFF0BF70)
val White = Color(0xFFFFFFFF)

// New Expressive Light Theme Colors
val ExpressiveTeal_Light_Primary = Color(0xFF008080) // Teal
val ExpressiveTeal_Light_OnPrimary = Color(0xFFFFFFFF)
val ExpressiveTeal_Light_PrimaryContainer = Color(0xFFB2DFDB)
val ExpressiveTeal_Light_OnPrimaryContainer = Color(0xFF004D40)

val ExpressiveOrange_Light_Secondary = Color(0xFFFF8A65) // Deep Orange accent
val ExpressiveOrange_Light_OnSecondary = Color(0xFF000000)
val ExpressiveOrange_Light_SecondaryContainer = Color(0xFFFFCCBC)
val ExpressiveOrange_Light_OnSecondaryContainer = Color(0xFFC63F17)

val ExpressivePurple_Light_Tertiary = Color(0xFF9575CD) // Deep Purple accent
val ExpressivePurple_Light_OnTertiary = Color(0xFFFFFFFF)
val ExpressivePurple_Light_TertiaryContainer = Color(0xFFD1C4E9)
val ExpressivePurple_Light_OnTertiaryContainer = Color(0xFF512DA8)

val ExpressiveLight_Error = Color(0xFFB00020) // Standard Error Red
val ExpressiveLight_OnError = Color(0xFFFFFFFF)
val ExpressiveLight_ErrorContainer = Color(0xFFFCD8DF)
val ExpressiveLight_OnErrorContainer = Color(0xFFB00020)

val ExpressiveLight_Background = Color(0xFFFFF7F0) // A very light, warm off-white
val ExpressiveLight_OnBackground = Color(0xFF211A13)
val ExpressiveLight_Surface = Color(0xFFFFF7F0) // Same as background for a unified look
val ExpressiveLight_OnSurface = Color(0xFF211A13)
val ExpressiveLight_SurfaceVariant = Color(0xFFFDEEE0) // Slightly darker variant
val ExpressiveLight_OnSurfaceVariant = Color(0xFF50443A)
val ExpressiveLight_Outline = Color(0xFF837468)


// New Expressive Dark Theme Colors (example adjustments)
val ExpressiveTeal_Dark_Primary = Color(0xFF4DB6AC) // Lighter Teal for Dark theme
val ExpressiveTeal_Dark_OnPrimary = Color(0xFF003732)
val ExpressiveTeal_Dark_PrimaryContainer = Color(0xFF004D40)
val ExpressiveTeal_Dark_OnPrimaryContainer = Color(0xFFB2DFDB)

val ExpressiveOrange_Dark_Secondary = Color(0xFFFFAB91) // Lighter Deep Orange for Dark
val ExpressiveOrange_Dark_OnSecondary = Color(0xFF541F0A)
val ExpressiveOrange_Dark_SecondaryContainer = Color(0xFFC63F17) // Darker container
val ExpressiveOrange_Dark_OnSecondaryContainer = Color(0xFFFFCCBC)

val ExpressivePurple_Dark_Tertiary = Color(0xFFB39DDB) // Lighter Deep Purple for Dark
val ExpressivePurple_Dark_OnTertiary = Color(0xFF320B5D)
val ExpressivePurple_Dark_TertiaryContainer = Color(0xFF512DA8) // Darker container
val ExpressivePurple_Dark_OnTertiaryContainer = Color(0xFFD1C4E9)

val ExpressiveDark_Error = Color(0xFFCF6679) // Standard Dark Error
val ExpressiveDark_OnError = Color(0xFF000000)
val ExpressiveDark_ErrorContainer = Color(0xFFB00020)
val ExpressiveDark_OnErrorContainer = Color(0xFFFCD8DF)

val ExpressiveDark_Background = Color(0xFF1A120B) // Deep, warm dark brown
val ExpressiveDark_OnBackground = Color(0xFFEDE0D4)
val ExpressiveDark_Surface = Color(0xFF1A120B) // Same as background
val ExpressiveDark_OnSurface = Color(0xFFEDE0D4)
val ExpressiveDark_SurfaceVariant = Color(0xFF2C2015) // Slightly lighter variant
val ExpressiveDark_OnSurfaceVariant = Color(0xFFD5C3B5)
val ExpressiveDark_Outline = Color(0xFF9D8D80)


// Original palette (keeping for reference, will be replaced in Theme.kt)
val primaryLight = Color(0xFF123130)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF355352)
val onPrimaryContainerLight = Color(0xFFD2F3F1)
val secondaryLight = Color(0xFF7C5811)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF8C676)
val onSecondaryContainerLight = Color(0xFF513600)
val tertiaryLight = Color(0xFF4B635C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBD6CD)
val onTertiaryContainerLight = Color(0xFF29413B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF9F8)
val onBackgroundLight = Color(0xFF1A1C1C)
val surfaceLight = Color(0xFFFAF9F8)
val onSurfaceLight = Color(0xFF1A1C1C)
val surfaceVariantLight = Color(0xFFDDE4E3)
val onSurfaceVariantLight = Color(0xFF414848)
val outlineLight = Color(0xFF717878)
val outlineVariantLight = Color(0xFFC1C8C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3130)
val inverseOnSurfaceLight = Color(0xFFF1F1F0)
val inversePrimaryLight = Color(0xFFACCDCB)
val surfaceDimLight = Color(0xFFDADAD9)
val surfaceBrightLight = Color(0xFFFAF9F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3F2)
val surfaceContainerLight = Color(0xFFEEEEED)
val surfaceContainerHighLight = Color(0xFFE9E8E7)
val surfaceContainerHighestLight = Color(0xFFE3E2E1)

val primaryLightMediumContrast = Color(0xFF123130)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF355352)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF5B3D00)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF956E27)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2F4741)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF617A72)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF9F8)
val onBackgroundLightMediumContrast = Color(0xFF1A1C1C)
val surfaceLightMediumContrast = Color(0xFFFAF9F8)
val onSurfaceLightMediumContrast = Color(0xFF1A1C1C)
val surfaceVariantLightMediumContrast = Color(0xFFDDE4E3)
val onSurfaceVariantLightMediumContrast = Color(0xFF3D4444)
val outlineLightMediumContrast = Color(0xFF596060)
val outlineVariantLightMediumContrast = Color(0xFF757C7B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3130)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F1F0)
val inversePrimaryLightMediumContrast = Color(0xFFACCDCB)
val surfaceDimLightMediumContrast = Color(0xFFDADAD9)
val surfaceBrightLightMediumContrast = Color(0xFFFAF9F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F3F2)
val surfaceContainerLightMediumContrast = Color(0xFFEEEEED)
val surfaceContainerHighLightMediumContrast = Color(0xFFE9E8E7)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE3E2E1)

val primaryLightHighContrast = Color(0xFF062726)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF2A4847)
// ... (rest of the original palette definitions can be kept for reference or removed if no longer needed)
// For brevity in this diff, I am omitting the rest of the old palette,
// but in practice, one might comment it out or remove it gradually.

val primaryDark = Color(0xFFACCDCB) // This is an old color, will be replaced by ExpressiveDark
val onPrimaryDark = Color(0xFF173534)
val primaryContainerDark = Color(0xFF1C3B3A)
val onPrimaryContainerDark = Color(0xFFACCCCA)
val secondaryDark = Color(0xFFFFE9CC)
val onSecondaryDark = Color(0xFF432C00)
val secondaryContainerDark = Color(0xFFEBBA6C)
val onSecondaryContainerDark = Color(0xFF462F00)
val tertiaryDark = Color(0xFFD8F4EA)
val onTertiaryDark = Color(0xFF1D352F)
val tertiaryContainerDark = Color(0xFFAFCAC1)
val onTertiaryContainerDark = Color(0xFF213933)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121413)
val onBackgroundDark = Color(0xFFE3E2E1)
val surfaceDark = Color(0xFF121413)
val onSurfaceDark = Color(0xFFE3E2E1)
val surfaceVariantDark = Color(0xFF414848)
val onSurfaceVariantDark = Color(0xFFC1C8C7)
val outlineDark = Color(0xFF8B9291)
val outlineVariantDark = Color(0xFF414848)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E1)
val inverseOnSurfaceDark = Color(0xFF2F3130)
val inversePrimaryDark = Color(0xFF466463)
val surfaceDimDark = Color(0xFF121413)
val surfaceBrightDark = Color(0xFF383939)
val surfaceContainerLowestDark = Color(0xFF0D0E0E)
val surfaceContainerLowDark = Color(0xFF1A1C1C)
val surfaceContainerDark = Color(0xFF1E2020)
val surfaceContainerHighDark = Color(0xFF292A2A)
val surfaceContainerHighestDark = Color(0xFF343535)

val primaryDarkMediumContrast = Color(0xFFB1D1CF)
val onPrimaryDarkMediumContrast = Color(0xFF001A19)
val primaryContainerDarkMediumContrast = Color(0xFF779795)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFE9CC)
val onSecondaryDarkMediumContrast = Color(0xFF432C00)
val secondaryContainerDarkMediumContrast = Color(0xFFEBBA6C)
val onSecondaryContainerDarkMediumContrast = Color(0xFF120900)
val tertiaryDarkMediumContrast = Color(0xFFD8F4EA)
val onTertiaryDarkMediumContrast = Color(0xFF1D352F)
val tertiaryContainerDarkMediumContrast = Color(0xFFAFCAC1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF00100C)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121413)
val onBackgroundDarkMediumContrast = Color(0xFFE3E2E1)
val surfaceDarkMediumContrast = Color(0xFF121413)
val onSurfaceDarkMediumContrast = Color(0xFFFBFAFA)
val surfaceVariantDarkMediumContrast = Color(0xFF414848)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC5CCCB)
val outlineDarkMediumContrast = Color(0xFF9DA4A3)
val outlineVariantDarkMediumContrast = Color(0xFF7D8484)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E2E1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A2A)
val inversePrimaryDarkMediumContrast = Color(0xFF2F4D4C)
val surfaceDimDarkMediumContrast = Color(0xFF121413)
val surfaceBrightDarkMediumContrast = Color(0xFF383939)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0E0E)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1C1C)
val surfaceContainerDarkMediumContrast = Color(0xFF1E2020)
val surfaceContainerHighDarkMediumContrast = Color(0xFF292A2A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF343535)

val primaryDarkHighContrast = Color(0xFFEAFFFD)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB1D1CF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF7)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFF4C373)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFECFFF8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFB6D1C8)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF121413)
val onBackgroundDarkHighContrast = Color(0xFFE3E2E1)
val surfaceDarkHighContrast = Color(0xFF121413)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF414848)
val onSurfaceVariantDarkHighContrast = Color(0xFFF5FCFB)
val outlineDarkHighContrast = Color(0xFFC5CCCB)
val outlineVariantDarkHighContrast = Color(0xFFC5CCCB)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E2E1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF0F2F2E)
val surfaceDimDarkHighContrast = Color(0xFF121413)
val surfaceBrightDarkHighContrast = Color(0xFF383939)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0E0E)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A1C1C)
val surfaceContainerDarkHighContrast = Color(0xFF1E2020)
val surfaceContainerHighDarkHighContrast = Color(0xFF292A2A)
val surfaceContainerHighestDarkHighContrast = Color(0xFF343535)







